In [1]:
# NOTE(Ryan): Censored cells set to 5

import pandas as pd
from io import StringIO

# Data Source: IRCC COGNOS – Detentions Datamart
# Prepared by: Statistics and Performance Metrics Unit, Intelligence and Enforcement Branch
# Extracted: 2026-07-02
# Notes: Detention statistics for the 2024 calendar year, broken down by country of citizenship.

# Citizenship,"# of Detainees"
df = pd.read_csv(StringIO("""\
Citizenship,Detainees
Afghanistan,11
Albania,16
Algeria,127
Angola,7
Antigua and Barbuda,5
Argentina,5
Australia,5
Azerbaijan,5
"Bahama Islands, The",14
Bahrain,5
Bangladesh,44
Barbados,20
Belarus,5
Belgium,10
Belize,5
Bermuda,5
Bolivia,6
Bosnia-Hercegovina,5
Brazil,25
British Dependent Territories Citizen,5
Bulgaria,5
Burkina-Faso,5
Burundi,10
Cambodia,5
Canada,5
Cape Verde Islands,5
"Chad, Republic of",5
Chile,115
Colombia,98
"Congo, Democratic Republic of the",32
"Congo, People's Republic of the",5
Costa Rica,5
Croatia,5
Cuba,14
Cyprus,5
Czech Republic,5
Democratic Republic of Sudan,10
Denmark,5
Dominica,5
Dominican Republic,27
Ecuador,10
Egypt,10
El Salvador,20
Eritrea,8
Ethiopia,8
Federal Republic of Cameroon,25
Federal Republic of Germany,12
Fiji,5
France,37
Gabon Republic,5
Gambia,6
Georgia,15
Ghana,53
Greece,7
Guatemala,27
"Guinea, Republic of",23
Guyana,12
Haiti,38
Honduras,11
Hong Kong SAR,9
Hungary,20
India,794
Iran,27
Iraq,18
Israel,12
Italy,10
Jamaica,118
Japan,17
Jordan,21
Kazakhstan,5
Kenya,26
"Korea, Republic of",27
Laos,5
Latvia,5
Lebanon,7
Liberia,5
Libya,5
Lithuania,5
Macedonia,5
Malaysia,5
"Mali, Republic of",5
Malta,5
Mauritius,5
Mexico,680
Moldova,5
"Mongolia, People's Republic of",5
Morocco,34
Myanmar (Burma),5
Namibia,6
Nepal,7
New Zealand,5
Nicaragua,8
Nigeria,305
Norway,5
Pakistan,39
Palestinian Authority (Gaza/West Bank),5
"Panama, Republic of",5
People's Republic of Benin,5
People's Republic of China,105
Peru,17
Philippines,81
Poland,5
Portugal,24
Republic of Djibouti,5
Republic of Indonesia,28
Republic of Ireland,17
Republic of Ivory Coast,5
Republic of South Africa,5
Republic of the Niger,5
Romania,282
Russia,8
Rwanda,10
Senegal,22
"Serbia, Republic of",5
Sierra Leone,7
Singapore,5
Slovak Republic,5
Socialist Republic of Vietnam,89
"Somalia, Democratic Republic of",41
"South Sudan, Republic of",7
Spain,75
Sri Lanka,56
St. Kitts-Nevis,9
St. Lucia,5
St. Vincent and the Grenadines,21
Stateless,15
Sweden,5
Switzerland,5
Syria,6
Taiwan,10
Tajikistan,5
Thailand,6
The Netherlands,9
"Togo, Republic of",5
"Trinidad and Tobago, Republic of",21
Tunisia,18
Turkey,22
UK - Brit. Nat. Overseas,5
UK - British citizen,87
Uganda,6
Ukraine,6
United Kingdom and Colonies,5
United Republic of Tanzania,6
United States of America,147
Unknown,5
Uzbekistan,5
Vanuatu,5
Venezuela,5
"Yemen, Republic of",5
Zambia,5
Zimbabwe,10"""))
df = df.sort_values(by="Detainees", ascending=False)
df

                  Citizenship  Detainees
61                      India        794
83                     Mexico        680
92                    Nigeria        305
109                   Romania        282
143  United States of America        147
..                        ...        ...
144                   Unknown          5
146                   Vanuatu          5
147                 Venezuela          5
148        Yemen, Republic of          5
149                    Zambia          5

[151 rows x 2 columns]

In [2]:
df.head(10)

                    Citizenship  Detainees
61                        India        794
83                       Mexico        680
92                      Nigeria        305
109                     Romania        282
143    United States of America        147
2                       Algeria        127
66                      Jamaica        118
27                        Chile        115
98   People's Republic of China        105
28                     Colombia         98