In [1]:
import gcinfo

gcinfo.list_resources(gcinfo.search_datasets(query='title:"Estimates of the number of non-permanent residents by type, quarterly"')["results"][0])

=== Estimates of the number of non-permanent residents by type, quarterly ===
ID: f8f711fa-6b75-4178-a60c-23093c071fc8
Org: Statistics Canada | Statistique Canada
Notes: This table provides quarterly estimates of the number of non-permanent residents by type for Canada, provinces and territories.<br>...
  [CSV     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/csv/17100121-fra.zip
  [CSV     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/csv/17100121-eng.zip
  [XML     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/sdmx/17100121-SDMX.zip

In [2]:
import requests
import zipfile
import io
import pandas as pd

url = "https://www150.statcan.gc.ca/n1/tbl/csv/17100121-eng.zip"

r = requests.get(url, timeout=60)
r.raise_for_status()

with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    print(z.namelist())
    files = [n for n in z.namelist() if n.endswith(".csv")]
    with z.open(files[0]) as f: # first file is data file 
        df = pd.read_csv(f)
    with z.open(files[1]) as f: # second file is metadata
        df_metadata = pd.read_csv(f)

['17100121.csv', '17100121_MetaData.csv']

In [17]:
df.to_csv(files[0])
df_metadata.to_csv(files[1])

In [26]:
df[["Non-permanent resident types", "VALUE"]]

,Non-permanent resident types,VALUE
0,"Total, non-permanent residents",1361855
1,"Total, asylum claimants, protected persons and related groups",168206
2,"Asylum claimants, protected persons and related groups with work permit only",94311
3,"Asylum claimants, protected persons and related groups with study permit only",1485
4,"Asylum claimants, protected persons and related groups with work and study permits",4094
...,...,...
3075,"Total, permit holders and their family members",200
3076,Work permit holders only,168
3077,Study permit holders only,9
3078,Work and study permit holders,4
3079,Other,19

In [22]:
print(df.shape)
print(df.head())

(3080, 15)
  REF_DATE     GEO           DGUID  \
0  2021-07  Canada  2021A000011124
1  2021-07  Canada  2021A000011124
2  2021-07  Canada  2021A000011124
3  2021-07  Canada  2021A000011124
4  2021-07  Canada  2021A000011124

                                                         Non-permanent resident types  \
0                                                      Total, non-permanent residents
1                       Total, asylum claimants, protected persons and related groups
2        Asylum claimants, protected persons and related groups with work permit only
3       Asylum claimants, protected persons and related groups with study permit only
4  Asylum claimants, protected persons and related groups with work and study permits

       UOM  UOM_ID SCALAR_FACTOR  SCALAR_ID       VECTOR  COORDINATE    VALUE  \
0  Persons     249         units          0  v1566927590         1.1  1361855
1  Persons     249         units          0  v1566927591         1.2   168206
2  Persons     249         units          0  v1566927592         1.3    94311
3  Persons     249         units          0  v1566927593         1.4     1485
4  Persons     249         units          0  v1566927594         1.5     4094

   STATUS  SYMBOL  TERMINATED  DECIMALS
0     NaN     NaN         NaN         0
1     NaN     NaN         NaN         0
2     NaN     NaN         NaN         0
3     NaN     NaN         NaN         0
4     NaN     NaN         NaN         0

,Non-permanent resident types,VALUE
0,"Total, non-permanent residents",1361855
1,"Total, asylum claimants, protected persons and related groups",168206
2,"Asylum claimants, protected persons and related groups with work permit only",94311
3,"Asylum claimants, protected persons and related groups with study permit only",1485
4,"Asylum claimants, protected persons and related groups with work and study permits",4094
...,...,...
3075,"Total, permit holders and their family members",200
3076,Work permit holders only,168
3077,Study permit holders only,9
3078,Work and study permit holders,4
3079,Other,19

In [23]:
print(df_metadata.shape)
df_metadata.head()

(62, 10)

,Cube Title,Product Id,CANSIM Id,URL,Cube Notes,Archive Status,Frequency,Start Reference Period,End Reference Period,Total number of dimensions
"Estimates of the number of non-permanent residents by type, quarterly",17100121,NaN,https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710012101,1;2;3;4;5;7;8;9,CURRENT - a cube available to the public and that is current,Quarterly,2021-07-01,2026-04-01,2.0,NaN
Dimension ID,Dimension name,Dimension Notes,Dimension Definitions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geography,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Non-permanent resident types,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dimension ID,Member Name,Classification Code,Member ID,Parent Member ID,Terminated,Member Notes,Member Definitions,NaN,NaN,NaN