In [1]:
import gcinfo
import pandas as pd
import matplotlib.pyplot as plt


gcinfo.search_titles("TFWP IMP")

Temporary Residents: Temporary Foreign Worker Program (TFWP) and International Mobility Program (IMP) Work Permit Holders – Monthly IRCC Updates
Temporary Residents: Work Permit Holders – Ad Hoc IRCC (Specialized Datasets)
Facts & Figures 2015: Immigration Overview - Temporary Residents – Annual IRCC Updates
Annual portraits of temporary admissions in Quebec - flow and stock as of December 31
Specialized Research Datasets: Temporary Resident – Ad Hoc IRCC (Specialized Datasets)
Facts and Figures 2016: Immigration Overview - Temporary Residents – Annual IRCC Updates

In [2]:
gcinfo.list_resources(gcinfo.search_datasets(query='title:"Temporary Residents: Temporary Foreign Worker Program (TFWP) and International Mobility Program (IMP) Work Permit Holders – Monthly IRCC Updates"')["results"][0])

=== Temporary Residents: Temporary Foreign Worker Program (TFWP) and International Mobility Program (IMP) Work Permit Holders – Monthly IRCC Updates ===
ID: 360024f2-17e9-4558-bfc1-3616485d65b9
Org: Immigration, Refugees and Citizenship Canada | Immigration, Réfugiés et Citoyenneté Canada
Notes: Temporary residents who are in Canada on a work permit in the observed calendar year. Datasets include Temporary Foreign Worker Program (TFWP) and International Mobility Program (IMP) work permit hold...
Citation: Immigration, Refugees and Citizenship Canada. Temporary Residents: Temporary Foreign Worker Program (TFWP) and International Mobility Program (IMP) Work Permit Holders – Monthly IRCC Updates
  [XLSX    ] Canada - International Mobility Program work permit holders by province/territory, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-IMP_PT_program_sign.xlsx
  [XLSX    ] Canada - International Mobility Program work permit holders by province/territory, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-IMP_PT_program_sign.xlsx
  [CSV     ] Canada - International Mobility Program work permit holders by province/territory of intended destination, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-IMP-PT_program.csv
  [XLSX    ] Canada - International Mobility Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-IMP_gender_skill.xlsx
  [XLSX    ] Canada - International Mobility Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-IMP_gender_skill.xlsx
  [CSV     ] Canada - International Mobility Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-IMP-gender_skill.csv
  [XLSX    ] Canada – International Mobility Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-IMP CITZ.xlsx
  [XLSX    ] Canada – International Mobility Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-IMP CITZ.xlsx
  [CSV     ] Canada – International Mobility Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-IMP-CITZ.csv
  [XLSX    ] Canada - International Mobility Program work permit holders (work purpose only) on December 31st by province/territory and program
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-IMP_PT_program_year_end.xlsx
  [XLSX    ] Canada - International Mobility Program work permit holders (work purpose only) on December 31st by province/territory of intended destination and program
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP_annual-TR-work-IMP_PT_program_year_end.xlsx
  [XLSX    ] Canada – International Mobility Program Work Permit Holders under Post-Graduate Employment by Province/Territory and Census Metropolitan Area (CMA) of Intended Destination and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-PGWP_PT_CMA_sign.xlsx
  [XLSX    ] Canada – International Mobility Program Work Permit Holders under Post-Graduate Employment by Province/Territory and Census Metropolitan Area (CMA) of Intended Destination and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-PGWP_PT_CMA_sign.xlsx
  [XLSX    ] Canada - International Mobility Program (IMP) work permit holders under post-graduate employment by province/territory, Census Division and Census Subdivision of the Intended Destination and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-PGWP_PT_CSD_sign.xlsx
  [XLSX    ] Canada - International Mobility Program (IMP) work permit holders under post-graduate employment by province/territor, Census Division and Census Subdivision of the Intended Destination and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-PGWP_PT_CSD_sign.xlsx
  [CSV     ] [rounded numbers - not for calculations] Canada - International Mobility Program (IMP) work permit holders under post-graduate employment by province/territory, Census Division and Census Subdivision of the Intended Destination and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-PGWP-PT_CSD.csv
  [XLSX    ] Canada – International Mobility Program Work Permit Holders under Post-Graduate Employment on December 31st by Province/Territory and Census Metropolitan Area (CMA) of Intended Destination
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-IMP_PT_CMA_year_end.xlsx
  [XLSX    ] Canada – International Mobility Program Work Permit Holders under Post-Graduate Employment on December 31st by Province/Territory and Census Metropolitan Area (CMA) of Intended Destination
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP_annual-TR-work-IMP_PT_CMA_year_end.xlsx
  [CSV     ] Canada – International Mobility Program Work Permit Holders under Post-Graduate Employment by Province/Territory and Census Metropolitan Area (CMA) of Intended Destination and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-PGWP-PT_CMA.csv
  [XLSX    ] Canada – All International Mobility Program (IMP) work permit holders on December 31st by country of citizenship and year
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/fr_odp_annual-tr-work-imp_citz_year_end_all_purpose.xlsx
  [XLSX    ] Canada – All International Mobility Program (IMP) work permit holders on December 31st by country of citizenship and year
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/en_odp_annual-tr-work-imp_citz_year_end_all_purpose.xlsx
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-TFWP_PT_program_sign.xlsx
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-TFWP_PT_program_sign.xlsx
  [CSV     ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, program and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-TFWP-PT_program.csv
  [XLSX    ] Canada – Temporary Foreign Worker Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-TFWP CITZ.xlsx
  [XLSX    ] Canada – Temporary Foreign Worker Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-TFWP CITZ.xlsx
  [CSV     ] Canada – Temporary Foreign Worker Program Work Permit Holders by Country of Citizenship and Year in which Permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-TFWP-CITZ.csv
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-TFWP_gender_skill_sign.xlsx
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-TFWP_gender_skill_sign.xlsx
  [CSV     ] Canada - Temporary Foreign Worker Program work permit holders by gender, occupational skill level and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-TFWP-gender_skill.csv
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-TFWP_PT_NOC4_sign.xlsx
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-TFWP_PT_NOC4_sign.xlsx
  [CSV     ] Canada - Temporary Foreign Worker Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-TFWP-PT_NOC4.csv
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders on December 31st by province/territory of intended destination and program
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-TFW_PT_program_year_end.xlsx
  [XLSX    ] Canada - Temporary Foreign Worker Program work permit holders on December 31st by province/territory of intended destination and program
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP_annual-TR-work-TFW_PT_program_year_end.xlsx
  [XLSX    ] Canada – Temporary Foreign Worker Program (TFWP) work permit holders on December 31st by country of citizenship
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-TFW_CITZ_year_end.xlsx
  [XLSX    ] Canada – Temporary Foreign Worker Program (TFWP) work permit holders on December 31st by country of citizenship
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP_annual-TR-work-TFW_CITZ_year_end.xlsx
  [XLSX    ] Canada - Work permit holders for Humanitarian & Compassionate purposes by country of citizenship and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-HC_citizenship_sign.xlsx
  [XLSX    ] Canada - Work permit holders for Humanitarian & Compassionate purposes by country of citizenship and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-HC_citizenship_sign.xlsx
  [CSV     ] Canada - Work permit holders for Humanitarian & Compassionate purposes by country of citizenship and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-HC_citizenship.csv
  [XLSX    ] Canada - Work permit holders for Humanitarian & Compassionate purposes by gender, age and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-HC_gender_age_sign.xlsx
  [XLSX    ] Canada - Work permit holders for Humanitarian & Compassionate purposes by gender, age and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-HC_gender_age_sign.xlsx
  [CSV     ] Canada - Work permit holders for Humanitarian & Compassionate purposes by gender, age and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-HC_gender_age.csv
  [XLSX    ] Canada - Work permit holders for Humanitarian and Compassionate purposes by Province/Territory and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-HC_PT_sign.xlsx
  [XLSX    ] Canada - Work permit holders for Humanitarian and Compassionate purposes by Province/Territory and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-HC_PT_sign.xlsx
  [CSV     ] Canada - Work permit holders for Humanitarian and Compassionate purposes by Province/Territory of Intended Destination and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-HC_PT.csv
  [XLSX    ] Canada - International Mobility Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP-TR-Work-IMP_PT_NOC4.xlsx
  [XLSX    ] Canada - International Mobility Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/FR_ODP-TR-Work-IMP_PT_NOC4.xlsx
  [CSV     ] Canada - International Mobility Program work permit holders by province/territory of intended destination, intended occupation (4-digit NOC 2011) and year in which permit(s) became effective
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/ODP-TR-Work-IMP-PT_NOC4.csv
  [XLSX    ] Canada – International Mobility Program (IMP) work permit holders (for work purposes only) on December 31st by country of citizenship and year
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/en_odp_annual-tr-work-imp_citz_year_end.xlsx
  [XLSX    ] Canada – International Mobility Program (IMP) work permit holders (for work purposes only) on December 31st by country of citizenship and year
           https://www.ircc.canada.ca/opendata-donneesouvertes/data/fr_odp_annual-tr-work-imp_citz_year_end.xlsx

In [3]:
df_tfw = gcinfo.download_xlsx("https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-TFW_PT_program_year_end.xlsx")
df_tfw.head()

Using cached file: cache\EN_ODP_annual-TR-work-TFW_PT_program_year_end.xlsx

,"Canada - Temporary Foreign Worker Program (TFWP) work permit holders on December 31st by Province/Territory of intended destination and program, 2000 - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Province/territory and program,NaN,NaN,2000,2001,2002,2003,2004,2005,2006,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2,NaN,NaN,Live-In Caregiver Program,--,--,--,--,5,5,10,...,35,25,5,--,--,0,0,0,0,0
3,NaN,NaN,Live-In Caregiver Occupations,--,--,--,--,--,--,0,...,--,5,5,--,--,--,--,--,0,--
4,NaN,Live-In Caregivers,NaN,--,5,--,--,5,10,10,...,40,30,15,--,--,--,--,--,0,--

In [4]:
df_imp = gcinfo.download_xlsx("https://www.ircc.canada.ca/opendata-donneesouvertes/data/EN_ODP_annual-TR-work-IMP_PT_program_year_end.xlsx")
df_imp.head()

Using cached file: cache\EN_ODP_annual-TR-work-IMP_PT_program_year_end.xlsx

,"Canada - International Mobility Program (IMP) work permit holders on December 31st by province/territory of intended destination and program, 2000 - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Province/territory and program,NaN,NaN,NaN,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2,NaN,NaN,NaN,Non-Trade,0,0,0,0,0,0,...,5,--,--,--,--,--,0,0,--,5
3,NaN,NaN,NaN,North American Free Trade Agreement (NAFTA),90,85,75,95,80,75,...,405,430,385,340,310,160,45,--,0,0
4,NaN,NaN,NaN,Other Free Trade Agreement (FTA),5,--,--,5,--,5,...,30,25,15,10,--,--,--,--,10,--